"""add_followup_canonical_fields

Revision ID: 35879dc9da18
Revises: 4895d1d54c65
Create Date: 2026-08-25 20:16:50.940540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35879dc9da18'
down_revision: Union[str, Sequence[str], None] = '4895d1d54c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_ups', sa.Column('consultation_id', sa.String(length=36), nullable=True))
    op.add_column('follow_ups', sa.Column('created_by_role', sa.String(length=50), nullable=True))
    op.add_column('follow_ups', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('measurements_to_repeat', sa.JSON(), nullable=True))
    op.add_column('follow_ups', sa.Column('adherence_required', sa.Boolean(), nullable=True))
    op.add_column('follow_ups', sa.Column('escalation_conditions', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('follow_ups', sa.Column('completion_notes', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('symptoms_outcome', sa.String(length=50), nullable=True))
    op.add_column('follow_ups', sa.Column('sync_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_follow_ups_consultation_id'), 'follow_ups', ['consultation_id'], unique=False)
    op.create_foreign_key(None, 'follow_ups', 'consultations', ['consultation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'follow_ups', type_='foreignkey')
    op.drop_index(op.f('ix_follow_ups_consultation_id'), table_name='follow_ups')
    op.drop_column('follow_ups', 'sync_status')
    op.drop_column('follow_ups', 'symptoms_outcome')
    op.drop_column('follow_ups', 'completion_notes')
    op.drop_column('follow_ups', 'started_at')
    op.drop_column('follow_ups', 'escalation_conditions')
    op.drop_column('follow_ups', 'adherence_required')
    op.drop_column('follow_ups', 'measurements_to_repeat')
    op.drop_column('follow_ups', 'reason')
    op.drop_column('follow_ups', 'created_by_role')
    op.drop_column('follow_ups', 'consultation_id')
    # ### end Alembic commands ###
