"""add_reviewed_fields_to_testorder_and_followup

Revision ID: 41e6e53ff7a6
Revises: 35879dc9da18
Create Date: 2026-08-26 11:27:38.938870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e6e53ff7a6'
down_revision: Union[str, Sequence[str], None] = '35879dc9da18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_ups', sa.Column('reviewed_by_doctor_at', sa.DateTime(), nullable=True))
    op.add_column('follow_ups', sa.Column('reviewed_by_doctor_id', sa.String(length=36), nullable=True))
    op.add_column('test_orders', sa.Column('result', sa.Text(), nullable=True))
    op.add_column('test_orders', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('test_orders', sa.Column('reviewed_by_doctor_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_orders', 'reviewed_by_doctor_id')
    op.drop_column('test_orders', 'reviewed_at')
    op.drop_column('test_orders', 'result')
    op.drop_column('follow_ups', 'reviewed_by_doctor_id')
    op.drop_column('follow_ups', 'reviewed_by_doctor_at')
    # ### end Alembic commands ###
