"""add_government_scheme_tables

Revision ID: 4895d1d54c65
Revises: a9b8c7d6e5f4
Create Date: 2026-08-25 15:09:49.147350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4895d1d54c65'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_citizen_profiles_abha_reference'), 'citizen_profiles', ['abha_reference'], unique=True)
    op.create_index(op.f('ix_citizen_profiles_assigned_asha_id'), 'citizen_profiles', ['assigned_asha_id'], unique=False)
    op.create_index(op.f('ix_citizen_profiles_phone'), 'citizen_profiles', ['phone'], unique=False)
    op.alter_column('scheme_evaluation_results', 'last_verified',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheme_evaluation_results', 'last_verified',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_citizen_profiles_phone'), table_name='citizen_profiles')
    op.drop_index(op.f('ix_citizen_profiles_assigned_asha_id'), table_name='citizen_profiles')
    op.drop_index(op.f('ix_citizen_profiles_abha_reference'), table_name='citizen_profiles')
    # ### end Alembic commands ###
