"""Initial_PostgreSQL_Schema

Revision ID: 60c6625d3cb5
Revises: 
Create Date: 2026-08-24 10:20:01.281082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c6625d3cb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_title', sa.String(length=200), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('district_name', sa.String(length=150), nullable=True),
    sa.Column('block_name', sa.String(length=150), nullable=True),
    sa.Column('village_name', sa.String(length=150), nullable=True),
    sa.Column('symptom_group', sa.String(length=100), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=True),
    sa.Column('time_window_hours', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('URGENT', 'HIGH', 'FOLLOW_UP', 'ROUTINE', 'INFORMATION', name='casepriorityenum'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('signed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=True),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('district_name', sa.String(length=150), nullable=True),
    sa.Column('block_name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_code'), 'facilities', ['code'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'FOLLOW_UP', 'ROUTINE', 'INFORMATION', name='casepriorityenum'), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('scheme_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('scheme_code', sa.String(length=50), nullable=False),
    sa.Column('scheme_name', sa.String(length=200), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('reason_summary', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_checks_citizen_id'), 'scheme_checks', ['citizen_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'ASHA_WORKER', 'PHC_DOCTOR', 'DISTRICT_ADMIN', 'SYSTEM_ADMIN', name='userroleenum'), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_identifier'), 'users', ['identifier'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('citizen_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('age_estimate', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('village_id', sa.String(length=36), nullable=True),
    sa.Column('village_name', sa.String(length=150), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('abha_reference', sa.String(length=50), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=True),
    sa.Column('gestational_weeks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_profiles_user_id'), 'citizen_profiles', ['user_id'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('worker_type', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=True),
    sa.Column('facility_name', sa.String(length=150), nullable=True),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('district_name', sa.String(length=150), nullable=True),
    sa.Column('village_ids', sa.JSON(), nullable=True),
    sa.Column('professional_registration', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_profiles_user_id'), 'worker_profiles', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'FOLLOW_UP', 'ROUTINE', 'INFORMATION', name='casepriorityenum'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ASHA_ASSIGNED', 'ASHA_ACKNOWLEDGED', 'CITIZEN_CONTACTED', 'VISIT_SCHEDULED', 'VISIT_IN_PROGRESS', 'ASHA_REVIEWED', 'REFERRED_TO_PHC', 'DOCTOR_ACKNOWLEDGED', 'PATIENT_ARRIVED', 'CONSULTATION_IN_PROGRESS', 'FOLLOW_UP_REQUIRED', 'REFERRED_TO_HIGHER_FACILITY', 'COMPLETED', 'UNREACHABLE', 'DECLINED', 'PENDING_SYNC', name='casestatusenum'), nullable=False),
    sa.Column('primary_concern', sa.Text(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('assigned_asha_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_asha_name', sa.String(length=150), nullable=True),
    sa.Column('assigned_facility_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_facility_name', sa.String(length=150), nullable=True),
    sa.Column('assigned_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_doctor_name', sa.String(length=150), nullable=True),
    sa.Column('safety_rule_triggered', sa.Boolean(), nullable=True),
    sa.Column('safety_rule_reason', sa.Text(), nullable=True),
    sa.Column('citizen_guidance_text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_asha_id'), 'cases', ['assigned_asha_id'], unique=False)
    op.create_index(op.f('ix_cases_assigned_doctor_id'), 'cases', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_cases_assigned_facility_id'), 'cases', ['assigned_facility_id'], unique=False)
    op.create_index(op.f('ix_cases_citizen_id'), 'cases', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_priority'), 'cases', ['priority'], unique=False)
    op.create_index(op.f('ix_cases_reference'), 'cases', ['reference'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('asha_visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('asha_worker_id', sa.String(length=36), nullable=False),
    sa.Column('visit_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=100), nullable=True),
    sa.Column('offline_client_id', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asha_visits_asha_worker_id'), 'asha_visits', ['asha_worker_id'], unique=False)
    op.create_index(op.f('ix_asha_visits_case_id'), 'asha_visits', ['case_id'], unique=False)
    op.create_index(op.f('ix_asha_visits_reference'), 'asha_visits', ['reference'], unique=True)
    op.create_table('consultations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=True),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('consultation_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('examination_notes', sa.Text(), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('provisional_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('confirmed_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('icd10_code', sa.String(length=50), nullable=True),
    sa.Column('care_plan_summary', sa.Text(), nullable=True),
    sa.Column('asha_followup_instructions', sa.Text(), nullable=True),
    sa.Column('followup_due_days', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_case_id'), 'consultations', ['case_id'], unique=False)
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consultations_reference'), 'consultations', ['reference'], unique=True)
    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=True),
    sa.Column('assigned_role', sa.Enum('CITIZEN', 'ASHA_WORKER', 'PHC_DOCTOR', 'DISTRICT_ADMIN', 'SYSTEM_ADMIN', name='userroleenum'), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'FOLLOW_UP', 'ROUTINE', 'INFORMATION', name='casepriorityenum'), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_assigned_user_id'), 'follow_ups', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_case_id'), 'follow_ups', ['case_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_due_at'), 'follow_ups', ['due_at'], unique=False)
    op.create_index(op.f('ix_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('from_asha_id', sa.String(length=36), nullable=True),
    sa.Column('from_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('to_facility_id', sa.String(length=36), nullable=False),
    sa.Column('to_facility_name', sa.String(length=200), nullable=True),
    sa.Column('urgency', sa.Enum('URGENT', 'HIGH', 'FOLLOW_UP', 'ROUTINE', 'INFORMATION', name='casepriorityenum'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_case_id'), 'referrals', ['case_id'], unique=False)
    op.create_index(op.f('ix_referrals_reference'), 'referrals', ['reference'], unique=True)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_index(op.f('ix_referrals_to_facility_id'), 'referrals', ['to_facility_id'], unique=False)
    op.create_table('symptom_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('spoken_term', sa.String(length=200), nullable=True),
    sa.Column('normalized_term', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('duration_text', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.Enum('CITIZEN_REPORTED', 'ASHA_CONFIRMED', 'DEVICE_MEASURED', 'AI_EXTRACTED', 'RULE_GENERATED', 'DOCTOR_CONFIRMED', name='informationsourceenum'), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_observations_case_id'), 'symptom_observations', ['case_id'], unique=False)
    op.create_table('vital_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('glucose_mg_dl', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('is_warning_sign', sa.Boolean(), nullable=True),
    sa.Column('source_type', sa.Enum('CITIZEN_REPORTED', 'ASHA_CONFIRMED', 'DEVICE_MEASURED', 'AI_EXTRACTED', 'RULE_GENERATED', 'DOCTOR_CONFIRMED', name='informationsourceenum'), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_records_case_id'), 'vital_records', ['case_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consultation_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('signature_ref', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_consultation_id'), 'prescriptions', ['consultation_id'], unique=False)
    op.create_table('test_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consultation_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('facility_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_orders_consultation_id'), 'test_orders', ['consultation_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('medicine', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.Column('dose', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('timing', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_test_orders_consultation_id'), table_name='test_orders')
    op.drop_table('test_orders')
    op.drop_index(op.f('ix_prescriptions_consultation_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_vital_records_case_id'), table_name='vital_records')
    op.drop_table('vital_records')
    op.drop_index(op.f('ix_symptom_observations_case_id'), table_name='symptom_observations')
    op.drop_table('symptom_observations')
    op.drop_index(op.f('ix_referrals_to_facility_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_reference'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_case_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_follow_ups_status'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_due_at'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_case_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_assigned_user_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_consultations_reference'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_case_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_asha_visits_reference'), table_name='asha_visits')
    op.drop_index(op.f('ix_asha_visits_case_id'), table_name='asha_visits')
    op.drop_index(op.f('ix_asha_visits_asha_worker_id'), table_name='asha_visits')
    op.drop_table('asha_visits')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_reference'), table_name='cases')
    op.drop_index(op.f('ix_cases_priority'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_citizen_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_facility_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_doctor_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_asha_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_worker_profiles_user_id'), table_name='worker_profiles')
    op.drop_table('worker_profiles')
    op.drop_index(op.f('ix_citizen_profiles_user_id'), table_name='citizen_profiles')
    op.drop_table('citizen_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_identifier'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheme_checks_citizen_id'), table_name='scheme_checks')
    op.drop_table('scheme_checks')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_facilities_code'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('cluster_alerts')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
