"""create_follow_up_escalations_table

Revision ID: 96cf257187ef
Revises: 41e6e53ff7a6
Create Date: 2026-08-26 11:45:39.076633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cf257187ef'
down_revision: Union[str, Sequence[str], None] = '41e6e53ff7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follow_up_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('consultation_id', sa.String(length=36), nullable=True),
    sa.Column('referral_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_asha_id', sa.String(length=36), nullable=False),
    sa.Column('priority', postgresql.ENUM('URGENT', 'HIGH', 'FOLLOW_UP', 'ROUTINE', 'INFORMATION', name='casepriorityenum', create_type=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('action_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_outcome', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_asha_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizen_profiles.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_escalations_assigned_asha_id'), 'follow_up_escalations', ['assigned_asha_id'], unique=False)
    op.create_index(op.f('ix_follow_up_escalations_assigned_doctor_id'), 'follow_up_escalations', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_follow_up_escalations_case_id'), 'follow_up_escalations', ['case_id'], unique=False)
    op.create_index(op.f('ix_follow_up_escalations_citizen_id'), 'follow_up_escalations', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_follow_up_escalations_follow_up_id'), 'follow_up_escalations', ['follow_up_id'], unique=True)
    op.create_index(op.f('ix_follow_up_escalations_status'), 'follow_up_escalations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_escalations_status'), table_name='follow_up_escalations')
    op.drop_index(op.f('ix_follow_up_escalations_follow_up_id'), table_name='follow_up_escalations')
    op.drop_index(op.f('ix_follow_up_escalations_citizen_id'), table_name='follow_up_escalations')
    op.drop_index(op.f('ix_follow_up_escalations_case_id'), table_name='follow_up_escalations')
    op.drop_index(op.f('ix_follow_up_escalations_assigned_doctor_id'), table_name='follow_up_escalations')
    op.drop_index(op.f('ix_follow_up_escalations_assigned_asha_id'), table_name='follow_up_escalations')
    op.drop_table('follow_up_escalations')
    # ### end Alembic commands ###
